### ISSUE TITLE
unity permission not enabling commands

### ISSUE THREAD

**Issue by DragonSlayer696** [randombyte-developer/unity#10]
So I added the unity permission to my list of permissions and it does not let me use the unity commands here is how i put it in i might have it set up wrong.

![asdawda](https://user-images.githubusercontent.com/46175643/54502712-b60af380-48f1-11e9-9e61-5f7db0fe0ad6.PNG)

**Comment by randombyte-developer** [comment]
Read https://github.com/lucko/LuckPerms/wiki/Verbose

Execute `lp verbose on`, run the commands of unity, execute `lp verbose record` and send the link.

**Comment by DragonSlayer696** [comment]
It now works I don't understand but As soon as i go to do this the commands now works, Thank you for the response sorry for wasting your time.
