### ISSUE TITLE
prefix needs to follow nucleus a bit better

### ISSUE THREAD

**Issue by KhaozFrost** [randombyte-developer/unity#6]
Nucleus chat prefix

When using Nucleus you can show you status in chat with the token {{pl:unity:marry}}. Read https://nucleuspowered.org/docs/modules/chat.html for more information.

currently using: 
prefix="{{prefix}} &8[&e{%level%}&8] {{o:team:s}}{{displayname}}{{o:leader}}{{pl:unity:marry}} {{suffix}} &7»&r "

the issue is having to put a space behind the unity placeholder causes ugly chat spaces that should be there. {{pl:unity:marry}} {{suffix}} &7»

i'm wondering if you could include something more like the :s at the end of the placeholder to add a space afterwards so: 

{{pl:unity:marry}} - no space
{{pl:unity:marry:s}} - space afterwards 

**Custom Prefixes**
Nucleus, as of 0.9, supports custom tokens other than “prefix” and “suffix”. In the chat formatting string, you can add the following tags:
    {{o:[option-name]}} - replaced by the text in option “rank”, if any.
    {{o:[option-name]:s}} - replaced by the text in option “rank”, if any. If there is text in the option, adds a space afterwards.

**Comment by KhaozFrost** [comment]
just looked at the config a bit and just found 
married-prefix="&c❤ " can just add a space in here so nvm.

**Comment by randombyte-developer** [comment]
Yeah, cool that you found it yourself! :+1:
