### ISSUE TITLE
Cooldown on /marry 

### ISSUE THREAD

**Issue by Shybella** [randombyte-developer/unity#8]
Is it possible to put a cooldown on how many marry requests you can send within a set cooldown

**Comment by randombyte-developer** [comment]
You can set a divorce cooldown in the config. Does that work for you?

**Comment by Shybella** [comment]
Yeah, that works great.

I was wanting a cooldown for marry requests. I have a few players that like to spam /marry on everyone until someone marries them. 

Punishing doesn't fix the problem as another just does the same thing.

I was going to make a kt-skript to add a cooldown but wanting to ask here first.

**Comment by randombyte-developer** [comment]
I don't have any plans to add that kind of cooldown in the future. Maybe command utils can make it work for you or go ahead with kt skript.
